[project]
name = 'template-format'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.template-example]
path = 'contracts/template-example.clar'
clarity_version = 3
epoch = 3.1

[contracts.token-example]
path = 'contracts/token-example.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
